# rag_core/state.py

"""
GraphState — The shared state schema for the entire LangGraph agent.

WHY THIS MATTERS:
    LangGraph works like an assembly line. Each node (Planner, Retriever,
    Responder, MemorySaver) is a station on that line. The GraphState is
    the "tray" that moves between stations — each station reads from it,
    does its job, and writes its results back to it.

    If this schema is wrong, the whole graph breaks. Define it carefully.
"""

from typing import TypedDict, Annotated, List
import operator


class GraphState(TypedDict):
    """
    TypedDict gives us:
    1. Type hints — Pylance warns us when we use wrong types
    2. Dict interface — LangGraph nodes return plain dicts (partial updates)
    3. No class overhead — lightweight, serializable

    Every field here is either READ by a node or WRITTEN by a node.
    """

    # ─── INPUT ────────────────────────────────────────────────────────────────
    query: str
    # The raw user question. Set at graph entry. Never modified after.
    # Example: "What is the refund policy for premium subscribers?"

    # ─── PLANNER OUTPUT ───────────────────────────────────────────────────────
    intent: str
    # Classified by the Planner node. Controls graph routing.
    # Values: "rag" | "chitchat" | "out_of_scope"
    # "rag"          → needs document retrieval (go to Retriever)
    # "chitchat"     → casual conversation (skip Retriever, go to Responder)
    # "out_of_scope" → not answerable (skip Retriever, go to Responder)

    # ─── RETRIEVER OUTPUT ─────────────────────────────────────────────────────
    retrieved_docs: List[dict]
    # Raw documents returned by Qdrant vector search.
    # Each dict: {"id": str, "text": str, "score": float, "metadata": dict}
    # These are NOT yet reranked — order may not be optimal.

    reranked_docs: List[dict]
    # Documents after FlashRank reranking.
    # Same structure as retrieved_docs but reordered by semantic relevance.
    # The Responder uses THIS, not retrieved_docs.

    # ─── RESPONDER OUTPUT ─────────────────────────────────────────────────────
    response: str
    # The final answer generated by Groq (Llama 3.3 70B).
    # This is what gets returned to the user.

    # ─── MEMORY ───────────────────────────────────────────────────────────────
    chat_history: Annotated[List[dict], operator.add]
    # Conversation history across multiple turns.
    # WHY Annotated with operator.add?
    #   Normal TypedDict fields get REPLACED when a node returns them.
    #   With operator.add, LangGraph APPENDS instead of replaces.
    #   So each turn's {"role": ..., "content": ...} gets added to the list
    #   without overwriting previous turns. This is how memory works.
    # Each entry: {"role": "user" | "assistant", "content": str}

    # ─── OBSERVABILITY ────────────────────────────────────────────────────────
    metadata: dict
    # Bag for tracking info — token counts, timing, retrieval scores etc.
    # Used by LangSmith and Logfire in Phase 5. Define it now, fill it later.
    # Example: {"tokens_used": 412, "retrieval_score": 0.87, "model": "llama-3.3-70b"}
